name: Debian12-XRDP

on:
  workflow_dispatch:

jobs:
  debian-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    container:
      image: debian:12

    steps:
      - name: Update System
        run: |
          apt update
          apt install -y sudo wget curl gnupg2 software-properties-common

      - name: Install XFCE + XRDP
        run: |
          apt install -y xfce4 xfce4-goodies xrdp dbus-x11

          echo xfce4-session > /etc/skel/.xsession

          systemctl enable xrdp || true

      - name: Create User
        run: |
          useradd -m -s /bin/bash RDP
          echo "RDP:Password123!" | chpasswd
          usermod -aG sudo RDP
          echo xfce4-session > /home/RDP/.xsession
          chown RDP:RDP /home/RDP/.xsession

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        run: |
          tailscaled &
          sleep 5

          tailscale up \
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
            --hostname=github-debian

      - name: Show Connection
        run: |
          echo "======================"
          echo "User : RDP"
          echo "Pass : Password123!"
          echo "IP:"
          tailscale ip -4
          echo "======================"

      - name: Keep Alive
        run: |
          while true
          do
            date
            sleep 300
          done
